title:              Akshay Podagatlapalli
email:              akshay.podagatlapalli@gmail.com
description:        I Like Data!
author:             Akshay Podagatlapalli
baseurl:            ""
url:                "https://akshay-podagatlapalli.github.io"

# Social Profiles
github_username:    https://github.com/akshay-podagatlapalli
linkedin_username:  https://www.linkedin.com/in/akshaypalli/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
